env:
  AZURE_WEBAPP_NAME: your-app-name    
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  DOTNET_VERSION: '8'                 

name: GitHub Action CI/CD Workflow
on: 
    push:
        branches:
            - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Dotnet Build
        run: dotnet build "AspNetCoreSampleFeature\AspNetCoreFeature\AspNetCoreFeature.csproj"

      - name: Dotnet Test
        run: dotnet test "AspNetCoreSampleFeature\AspNetCoreFeatureTests\AspNetCoreFeatureTests\AspNetCoreFeatureTests.csproj"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: echo 
        run: echo "$secrets.TOKEN"

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
            context: ./AspNetCoreSampleFeature/AspNetCoreFeature
            push: true
            tags: ghcr.io/home-teach-bryan/asp-net-ore-feature:latest


      

      
  
